# Generated by Django 5.0.4 on 2024-05-04 20:36

import PetWatchApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOCATION',
            fields=[
                ('LOCATION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LOCATION_TYPE', models.CharField(choices=[('H', 'HOME'), ('F', 'FARM'), ('K', 'KENNEL')], max_length=1)),
                ('LOCATION_SIZE', models.IntegerField()),
                ('LOCATION_NUMBER_OF_OCCUPANTS', models.IntegerField()),
                ('LOCATION_HAS_KIDS', models.BooleanField()),
                ('LOCATION_HAS_FENCE', models.BooleanField()),
                ('LOCATION_HAS_PETS', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_PHOTO', models.FileField(upload_to=PetWatchApp.models.user_directory_path)),
                ('USER_FIRST_NAME', models.CharField(max_length=50)),
                ('USER_MID_INITIAL', models.CharField(max_length=1)),
                ('USER_LAST_NAME', models.CharField(max_length=50)),
                ('USER_PHONE', models.CharField(max_length=12)),
                ('USER_EMAIL', models.EmailField(max_length=254)),
                ('USER_ADDRESS', models.CharField(max_length=50)),
                ('USER_CITY', models.CharField(max_length=50)),
                ('USER_STATE', models.CharField(max_length=2)),
                ('USER_ZIPCODE', models.IntegerField()),
                ('USER_BIO', models.CharField(max_length=250)),
                ('USER_BIRTHDATE', models.DateField()),
                ('USER_AGE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REVIEW_TEXT', models.CharField(max_length=300)),
                ('REVIEWED_LOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetWatchApp.location')),
                ('REVIEWING_USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetWatchApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PET',
            fields=[
                ('PET_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PET_FIRST_NAME', models.CharField(max_length=50)),
                ('PET_TYPE', models.CharField(choices=[('D', 'DOG'), ('C', 'CAT'), ('L', 'LIZARD')], max_length=1)),
                ('PET_BREED', models.CharField(max_length=50)),
                ('PET_WEIGHT', models.DecimalField(decimal_places=1, max_digits=4)),
                ('PET_VACCINATION_STATUS', models.BooleanField()),
                ('PET_OWNER_USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetWatchApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='LOCATION_OWNER_USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetWatchApp.user'),
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('EMPLOYEE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMPLOYEE_SSN', models.CharField(max_length=11)),
                ('EMPLOYEE_TITLE', models.CharField(max_length=50)),
                ('EMPLOYEE_PAY_TYPE', models.CharField(choices=[('H', 'HOURLY'), ('S', 'SALARY')], max_length=1)),
                ('EMPLOYEE_PAY_RATE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('EMPLOYEE_HIRE_DATE', models.DateField()),
                ('EMPLOYEE_USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetWatchApp.user')),
            ],
        ),
    ]
